### ISSUE TITLE
Editor not visible in Repeater or Builder

### ISSUE THREAD

**Issue by bariskanberkay** [amidesfahani/filament-tinyeditor#11]
When I want to use the editor in repeater or builder, I get the error I mentioned in the attachment.

![Ekran Resmi 2023-11-18 05 00 45](https://github.com/amidesfahani/filament-tinyeditor/assets/48731845/567cde1f-a589-432d-b55f-d51e3608d89b)

**Comment by yash-tiwari18** [comment]
Editor is not loading on my project either but the error is different,

Uncaught TypeError: i is not a constructor at N1 (tinymce.min.js:9:342964) at Tx.<anonymous> (tinymce.min.js:9:345352) at Array.<anonymous> (tinymce.min.js:9:98656) at ce (tinymce.min.js:9:4670) at u (tinymce.min.js:9:98602) at tinymce.min.js:9:98418 at a.onload (tinymce.min.js:9:97183)

**Comment by duongductrong** [comment]
> When I want to use the editor in repeater or builder, I get the error I mentioned in the attachment.
> 
> ![Ekran Resmi 2023-11-18 05 00 45](https://private-user-images.githubusercontent.com/48731845/283966390-567cde1f-a589-432d-b55f-d51e3608d89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NjkwMzAsIm5iZiI6MTcwMDk2ODczMCwicGF0aCI6Ii80ODczMTg0NS8yODM5NjYzOTAtNTY3Y2RlMWYtYTU4OS00MzJkLWI1NWYtZDUxZTM2MDhkODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAzMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMDUzMTcyN2M4MTNkZmY2YjBjOTMxM2JkOWI3ZjUzMzA0MmUzMmE4YTA3ZTBkZTU1ZTExZDQ1OWVjMmZkZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyr0s_CpV2DJ8eMzzxsINk3ms0Qiun-66uxjdK7U6yo)

I got the same issue

**Comment by duongductrong** [comment]
That's my solution (temp) to resolve this issue:

Open blade file: resources/views/vendor/filament-tinyeditor/tiny-editor.blade.php

The first, you should add `.rand()` or any method to generate new id each re-render of livewire component
```php
 $textareaID = "tiny-editor-" . str_replace([".", "#", '$'], "", $getId()) . rand();
```

The second is the setup method. You add the optional chaining object to the id

```php
                    if (!window.tinySettingsCopy.some(obj => obj?.id === editor?.settings?.id)) {
                        window.tinySettingsCopy.push(editor.settings);
                    }
```

**Comment by bariskanberkay** [comment]
> That's my solution (temp) to resolve this issue:
> 
> Open blade file: resources/views/vendor/filament-tinyeditor/tiny-editor.blade.php
> 
> The first, you should add `.rand()` or any method to generate a new id each re-render of livewire component
> 
> ```
>  $textareaID = "tiny-editor-" . str_replace([".", "#", '$'], "", $getId()) . rand();
> ```
> 
> The second is the `setup` method. You add the optional chaining object to the id
> 
> ```
>                     if (!window.tinySettingsCopy.some(obj => obj?.id === editor?.settings?.id)) {
>                         window.tinySettingsCopy.push(editor.settings);
>                     }
> ```
> 
> For this setup, that's work for me

The Editor works with this method. Generating a unique key might be a better solution.
