### ISSUE TITLE
Auto hidden editor when I switching to another language using (Translatable)

### ISSUE THREAD

**Issue by duongductrong** [amidesfahani/filament-tinyeditor#13]
https://github.com/amidesfahani/filament-tinyeditor/assets/39333905/e2cf38a3-0e95-4af1-837a-ca4009b736e9

Filamentphp version: 3

**Comment by amidesfahani** [comment]
@duongductrong what plugin you are using to switch between languages?

**Comment by scarm01** [comment]
He's using this plugin [https://filamentphp.com/plugins/filament-spatie-translatable](https://filamentphp.com/plugins/filament-spatie-translatable)

I'm experiencing the same issue

**Comment by scarm01** [comment]
@duongductrong this solution is fixing the issue for me https://github.com/amidesfahani/filament-tinyeditor/issues/11#issuecomment-1826483304
