### ISSUE TITLE
Script with ID [tinymce-lang-es] not found for package [amidesfahani/filament-tinyeditor].

### ISSUE THREAD

**Issue by DanielLiberato** [amidesfahani/filament-tinyeditor#2]
Hello, First of all, thank you for creating such a wonderful plugin.

I only had one problem when my app uses the Spanish 'es' language.

![image](https://github.com/amidesfahani/filament-tinyeditor/assets/81873713/23227ca4-7d00-4a8b-831e-c217645e7f0e)

![image](https://github.com/amidesfahani/filament-tinyeditor/assets/81873713/54c24941-6043-4714-be22-94bde721a3be)

**Comment by tomasagradaweb** [comment]
I have the same problem, any solution?

**Comment by amidesfahani** [comment]
@tomasagradaweb cool idead. thanks

**Comment by amidesfahani** [comment]
Fixed in https://github.com/amidesfahani/filament-tinyeditor/pull/3

**Comment by amidesfahani** [comment]
a new option value added to config file. you can now override languages or add missing ones.
```
languages => [
      'fa' => 'https://cdn.jsdelivr.net/npm/tinymce-i18n@23.10.9/langs6/fa.min.js',
      'es' => 'https://cdn.jsdelivr.net/npm/tinymce-i18n@23.10.9/langs6/es.min.js',
      'ja' => asset('assets/ja.min.js')
]
```
