### ISSUE TITLE
Strange issue with dark mode

### ISSUE THREAD

**Issue by flord22** [amidesfahani/filament-tinyeditor#22]
For some reason when changing the darkMode config value, the result is not what I would expect.

> darkMode: auto|force|class|media|false

auto: **dark** on both light and dark filament theme
force: **dark** on both light and dark filament theme
class: both light and dark work as expected but only on page refresh, it doesn't auto update on filament theme change.
media: **dark** on both light and dark filament theme
false: **dark** on both light and dark filament theme

Do you know why would this behavior occur?

**Comment by amidesfahani** [comment]
to disable dark Mode set it to false without quotations
`'darkMode' => false,`
media fixed
perfectly works on all options
