### ISSUE TITLE
image plugin - how to implement image_list & image_advtab

### ISSUE THREAD

**Issue by Teddyluke** [amidesfahani/filament-tinyeditor#27]
is it possible to implements those 2 parameters to the editor?

**Comment by amidesfahani** [comment]
`
TinyEditor::make('content')->required()
->imageList([
    ['title' => 'Cat', 'value' => 'cat.png'],
    ['title' => 'Dogs', 'menu' => [
        ['title' => 'Alaskan Husky', 'value' => 'husky.jpg'],
        ['title' => 'Dingo', 'value' => 'dingo.png'],
        ['title' => 'Swedish Lapphund', 'value' => 'swedish_lapphund.gif']
    ]]
])
->options([
    'showMenuBar' => true,
    'direction' => 'ltr',
    'darkMode' => false,
    'image_advtab' => true,
])
`

update to latest version
