### ISSUE TITLE
Upgrade to TinyMCE 7 due to XSS Vulnerability in TinyMCE 6.8.1

### ISSUE THREAD

**Issue by akaflipper** [amidesfahani/filament-tinyeditor#40]
Hi, 
got a composer vulnerability in TinyMCE .. 

[https://github.com/advisories/GHSA-5359-pvf2-pw78]

is it possible to either update dependencies to 7 or to 

use convert_unsafe_embeds option to automatically convert object and embed elements respective of their type attribute to bypass this security issue?

thanks
Gary

**Comment by amidesfahani** [comment]
Hi Gary please use the latest version.

`"tinymce/tinymce": "^7.0"`

**Comment by akaflipper** [comment]
Thanks Amid, my composer wasn't noticing the bump to ^2.0 last week with the upgrade to tinymce 7.0
