### ISSUE TITLE
Cannot focus or type in tinymce modal

### ISSUE THREAD

**Issue by cloudenum** [amidesfahani/filament-tinyeditor#47]
This issue is very similar to what has been described here https://github.com/mohamedsabil83/filament-forms-tinyeditor/issues/32 and here https://github.com/tinymce/tinymce/issues/5169

- [filament-tinyeditor](https://github.com/amidesfahani/filament-tinyeditor) Version: 1.1.4
- [tinymce](https://github.com/tinymce/tinymce) Version: 6.8.4

**Comment by genonline** [comment]
I'm experiencing the same.  I can't insert a link, media or sample code.  Also, there console logs show deprecated features are currently enabled and have been removed in TinyMCE 7.0.
