### ISSUE TITLE
No editor visible

### ISSUE THREAD

**Issue by bubixon** [amidesfahani/filament-tinyeditor#5]
No editor visible:

Error console:

![image](https://github.com/amidesfahani/filament-tinyeditor/assets/41482154/b2894f5a-5710-4259-8e2d-3af5686d5ec4)

**Comment by amidesfahani** [comment]
@bubixon tiny js files not downloaded. currently to use this package you need an active internet connection.

**Comment by sud0su** [comment]
me too, the editor is not visible, and i got this error from console

<img width="634" alt="Screenshot 2023-11-06 at 09 11 04" src="https://github.com/amidesfahani/filament-tinyeditor/assets/6576959/7d3d6f1e-14d4-4edc-9dc6-c531e224738c">

**Comment by sweebee** [comment]
For me the same, `TypeError: i is not a constructor`.

**Comment by amidesfahani** [comment]
You can now choose your tiny provider. cloud or vendor
to use vendor version please publish public assets first
```bash
php artisan vendor:publish --provider="AmidEsfahani\FilamentTinyEditor\TinyeditorServiceProvider" --tag="public"
```

then change or add `provider` to `vendor` in `filament-tinyeditor.php` config file
```php
'provider' => 'cloud', // cloud|vendor
```

PR: https://github.com/amidesfahani/filament-tinyeditor/pull/10
