### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by blursolo** [amidesfahani/filament-tinyeditor#51]
I'm sorry but I can't figure out how to make this work.
I have added these libraries to my composer.json:

```
"amidesfahani/filament-tinyeditor": "^2.0",
"tinymce/tinymce": "^7.0",
```
Then I have published all the assets
and made changes to the config/filament-tinyeditor.php file:

```
'version' => [
        'tiny' => '7.2.1',
        'licence_key' => 'gpl',
    ],
'provider' => 'vendor',
```

for some reason I get the following JS error:
`Uncaught ReferenceError: theme is not defined`

When I downgrade to filament-tinyeditor 2.0.1 it works.

**Comment by crslp** [comment]
I can confirm that downgrading to 2.0.1 worked for me, too. Latest 2.0.5 were causing an syntax error in Livewire verdor file.

**Comment by amidesfahani** [comment]
https://github.com/amidesfahani/filament-tinyeditor/releases/tag/v2.0.6
