### ISSUE TITLE
[Feature Request] - add option to display editor with expanded toolbar by default

### ISSUE THREAD

**Issue by IVoyt** [amidesfahani/filament-tinyeditor#55]
TinyMCE has an API method to collapse/expand toolbar programmatically.
In your plugin implementation it is collapsed by default. I don't if it is TinyMCE's default behaviour but it would be great to have option to control this behaviour.

Here is more info about the API call https://github.com/tinymce/tinymce/pull/6010

**Comment by amidesfahani** [comment]
set toolbar mode to wrap
