### ISSUE TITLE
Error of formatting

### ISSUE THREAD

**Issue by LukasCCB** [amidesfahani/filament-tinyeditor#57]
It malfunctions, as in the images.
The text in the Editor is formatted and in the blade it is normal text. Only the colors are respected.

![image](https://github.com/user-attachments/assets/940bf2a2-bcce-4207-a617-fd4a6eea0a4f)
![image](https://github.com/user-attachments/assets/8878cb8b-eabc-45c4-b128-bb4913a8528e)
![image](https://github.com/user-attachments/assets/67e7ecc4-cbed-4686-9004-9a9bf8f2f693)

Laravel 11x
PHP 8.3
NGINX

**Comment by amidesfahani** [comment]
I checked this and the HTML content displays fine for me. Maybe the issue is with your CSS content.
