### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by dharen008** [amidesfahani/filament-tinyeditor#58]
Can this issue be fixed? Are you seeing the same console error as I am?

![image](https://github.com/user-attachments/assets/5a449fdf-60cf-4e58-b57b-8825546c4145)

**Comment by iron-viper** [comment]
@dharen008 did you try to use it https://github.com/amidesfahani/filament-tinyeditor/issues/52 ?

**Comment by dharen008** [comment]
> @dharen008 did you try to use it #52 ?

Not yet, I'm hoping the developer will fix it on the main files

**Comment by amidesfahani** [comment]
https://github.com/amidesfahani/filament-tinyeditor/issues/52#issuecomment-2292441100

**Comment by dharen008** [comment]
@amidesfahani after i tried to composer update, republish all assets and config file then npm update and build. theres a error showing and the tinyMCE is not showing

![image](https://github.com/user-attachments/assets/b3d828f1-b4d1-4e75-bbde-a45cc01cfe0a)
![image](https://github.com/user-attachments/assets/b047d339-d83e-465d-891b-86d9d2fb83ac)


![image](https://github.com/user-attachments/assets/41ef752c-88f7-46ed-a6f1-57344dad9974)
![image](https://github.com/user-attachments/assets/ac7513b0-b749-4cc5-9d64-aabd5f649b93)

**Comment by amidesfahani** [comment]
https://github.com/amidesfahani/filament-tinyeditor/releases/tag/v2.0.6

**Comment by willcastillo** [comment]
FWIW, 2.0.6 did not solve the issue for me. The problem is that TinyEditor::getResize() is retuning blank when not initialized. Hope it helps.

**Comment by willcastillo** [comment]
Actually... there are a lot of variables that are not being json encoded properly.

**Comment by dharen008** [comment]
I'm still having the same issue https://github.com/amidesfahani/filament-tinyeditor/issues/58#issuecomment-2293521848
is there any update on this? currently the TinyEditor is not showing on my end

**Comment by willcastillo** [comment]
@dharen008 Add `->resize('both')` to your TinyEditor()::make()

**Comment by dharen008** [comment]
Thank you, @willcastillo! It's working now, but unfortunately, the console is still showing an error related to the plugin template. According to the developer and this [link](https://github.com/amidesfahani/filament-tinyeditor/issues/52#issuecomment-2292441100), it seems this issue won't be fixed.

**Comment by willcastillo** [comment]
@dharen008 Yeah... the blade file has a lot of errors. Every json object is being encoded twice. Changing them from `{{ $var }}` to `{!! $var !!}`.

However... there are more issues down the road that makes it just not worth it for me to keep digging.

**Comment by amidesfahani** [comment]
@dharen008 please share you config in filament resource and tiny config file (if you made changes)

**Comment by dharen008** [comment]
i already fix it by manually replacing the config, css, js and resources view

using composer update, php artisan vendor:publish --provider="AmidEsfahani\FilamentTinyEditor\TinyeditorServiceProvider" and npm run build does not update the whole plugin. you need to manually update it or reinstall it
