### ISSUE TITLE
Alpine Expression Error: expected expression, got ',' message in 2.0.5 version

### ISSUE THREAD

**Issue by ivan-orlov-13** [amidesfahani/filament-tinyeditor#63]
After I updated the version from 2.0.4 to 2.0.5 I get an error in the editor and it does not render. I realized that the problem is in the "resize" line (I have added my own comment below), but I do not have this setting anywhere and I think this error is somewhere inside the library.

Alpine Expression Error: expected expression, got ','

Expression: "tinyeditor({
            state: $wire.entangle('data.full'),
            statePath: 'data.full',
            selector: '#tiny-editor-data-full-1362769597',
            plugins: 'accordion autoresize codesample directionality advlist autolink link image lists charmap preview anchor pagebreak searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media table emoticons template help',
            external_plugins: {},
            toolbar: 'undo redo removeformat | fontfamily fontsize fontsizeinput font_size_formats styles | bold italic underline | rtl ltr | alignjustify alignright aligncenter alignleft | numlist bullist outdent indent accordion | forecolor backcolor | blockquote table toc hr | image link anchor media codesample emoticons | visualblocks print preview wordcount fullscreen help',
            language: 'en',
            language_url: 'https://cdn.jsdelivr.net/npm/tinymce-i18n@23.10.9/langs6/en.min.js',
            directionality: 'ltr',
                                                min_height: 500,
                                                            min_width: 500,
                        resize: , <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  no default value here
            			skin: (document.querySelector('html').getAttribute('class').includes('dark') ? 'oxide-dark' : 'oxide'),
			content_css: (document.querySelector('html').getAttribute('class').includes('dark') ? 'dark' : 'default'),
			            toolbar_sticky: true,
            toolbar_sticky_offset: 64,
            toolbar_mode: 'floating',
            toolbar_location: 'auto',
            inline: false,
            toolbar_persist: false,
            menubar: false,
            relative_urls: false,
            remove_script_host: true,
            convert_urls: true,
            font_size_formats: '',
            fontfamily: '',
            setup: null,
            disabled: {},
            locale: 'en',
            placeholder: null,
            image_list: false,
                        images_upload_url: '',
                        image_advtab: false,
            image_description: true,
            image_class_list: [],
            license_key: 'gpl',
            custom_configs: {}
        })"

**Comment by hammad-somnowell** [comment]
Try This
https://github.com/amidesfahani/filament-tinyeditor/issues/58#issuecomment-2297746578
